/**
 * Generated by tsnapi — public API snapshot of `sv/src/index`
 */
// #region Types
export type Addon<Args extends OptionDefinition, Id extends string = string> = {
  id: Id;
  alias?: string;
  shortDescription?: string;
  homepage?: string;
  hidden?: boolean;
  options: Args;
  setup?: (_: Workspace & {
    dependsOn: (_: keyof typeof officialAddons) => void;
    unsupported: (_: string) => void;
    runsAfter: (_: keyof typeof officialAddons) => void;
  }) => MaybePromise<void>;
  run: (_: Workspace & {
    options: WorkspaceOptions<Args>;
    sv: SvApi;
    cancel: (_: string) => void;
  }) => MaybePromise<void>;
  nextSteps?: (_: Workspace & {
    options: WorkspaceOptions<Args>;
  }) => string[];
};
export type AddonDefinition<Id extends string = string> = Addon<Record<string, Question<any>>, Id>;
export type AddonInput = {
  readonly specifier: string;
  readonly options: string[];
};
export type AddonMap = Record<string, Addon<any, any>>;
export type AddonReference = {
  readonly specifier: string;
  readonly options: string[];
  readonly source: AddonSource;
};
export type AddonResult = {
  readonly id: string;
  readonly status: "success" | {
    canceled: string[];
  };
  readonly files: string[];
};
export type AddonSource = {
  readonly kind: "official";
  readonly id: string;
} | {
  readonly kind: "file";
  readonly path: string;
} | {
  readonly kind: "npm";
  readonly packageName: string;
  readonly npmUrl: string;
  readonly registryUrl: string;
  readonly tag: string;
};
export type BaseQuestion<Args extends OptionDefinition> = {
  question: string;
  group?: string;
  condition?: (_: OptionValues<Args>) => boolean;
};
export type BooleanQuestion = {
  type: "boolean";
  default: boolean;
};
export type ConfiguredAddon = PreparedAddon & {
  readonly answers: OptionValues<any>;
};
export type FileEditor = Workspace & {
  content: string;
};
export type FileType = {
  name: (_: Workspace) => string;
  condition?: ConditionDefinition;
  content: (_: FileEditor) => string;
};
export type InstallOptions<Addons extends AddonMap> = {
  cwd: string;
  addons: Addons;
  options: OptionMap<Addons>;
  packageManager?: AgentName;
};
export type LanguageType = (typeof languageTypes)[number];
export type LoadedAddon = {
  readonly reference: AddonReference;
  readonly addon: AddonDefinition;
};
export type MultiSelectQuestion<Value> = {
  type: "multiselect";
  default: NoInfer<Value[]>;
  options: Array<{
    value: Value;
    label?: string;
    hint?: string;
  }>;
  required: boolean;
};
export type NumberQuestion = {
  type: "number";
  default: number;
  validate?: (_: string | undefined) => string | Error | undefined;
  placeholder?: string;
};
export type OptionBuilder<T extends OptionDefinition> = {
  add<K extends string, const Q extends Question<T & Record<K, Q>>>(_: K, _: Q): OptionBuilder<T & Record<K, Q>>;
  build(): Prettify<T>;
};
export type OptionDefinition = Record<string, Question<any>>;
export type OptionMap<Addons extends AddonMap> = { [Id in Addons[keyof Addons]["id"]]: Partial<OptionValues<AddonById<Addons, Id>["options"]>> };
export type OptionValues<Args extends OptionDefinition> = { [K in keyof Args]: Args[K] extends StringQuestion ? string : Args[K] extends BooleanQuestion ? boolean : Args[K] extends NumberQuestion ? number : Args[K] extends SelectQuestion<infer Value> ? Value : Args[K] extends MultiSelectQuestion<infer Value> ? Value[] : "ERROR: The value for this type is invalid. Ensure that the `default` value exists in `options`." };
export type PreparedAddon = LoadedAddon & {
  readonly setupResult: SetupResult;
};
export type Question<Args extends OptionDefinition = OptionDefinition> = BaseQuestion<Args> & (BooleanQuestion | StringQuestion | NumberQuestion | SelectQuestion<any> | MultiSelectQuestion<any>);
export type SelectQuestion<Value> = {
  type: "select";
  default: NoInfer<Value>;
  options: Array<{
    value: Value;
    label?: string;
    hint?: string;
  }>;
};
export type SetupResult = {
  dependsOn: string[];
  unsupported: string[];
  runsAfter: string[];
};
export type StringQuestion = {
  type: "string";
  default: string;
  validate?: (_: string | undefined) => string | Error | undefined;
  placeholder?: string;
};
export type SvApi = {
  pnpmBuildDependency: (_: string) => void;
  dependency: (_: string, _: string) => void;
  devDependency: (_: string, _: string) => void;
  execute: (_: string[], _: "inherit" | "pipe") => Promise<void>;
  file: (_: string, _: (_: string) => string | false) => void;
};
export type TemplateType = (typeof templateTypes)[number];
export type Workspace = {
  cwd: string;
  dependencyVersion: (_: string) => string | undefined;
  language: "ts" | "js";
  file: {
    viteConfig: "vite.config.js" | "vite.config.ts";
    svelteConfig: "svelte.config.js" | "svelte.config.ts";
    typeConfig: "jsconfig.json" | "tsconfig.json" | undefined;
    stylesheet: `${string}/layout.css` | "src/app.css";
    package: "package.json";
    gitignore: ".gitignore";
    prettierignore: ".prettierignore";
    prettierrc: ".prettierrc";
    eslintConfig: "eslint.config.js";
    vscodeSettings: ".vscode/settings.json";
    vscodeExtensions: ".vscode/extensions.json";
    getRelative: ({
      from,
      to
    }: {
      from?: string;
      to: string;
    }) => string;
    findUp: (_: string) => string;
  };
  isKit: boolean;
  directory: {
    src: string;
    lib: string;
    kitRoutes: string;
  };
  packageManager: AgentName;
};
export type WorkspaceOptions<Args extends OptionDefinition> = OptionValues<Args>;
// #endregion

// #region Functions
export declare function add<Addons extends AddonMap>({
  addons,
  cwd,
  options,
  packageManager
}: InstallOptions<Addons>): Promise<ReturnType<typeof applyAddons>>;
export declare function create(_: Options): void;
/** @deprecated */
export declare function create(_: string, _: Omit<Options, "cwd">): void;
export declare function defineAddon<const Id extends string, Args extends OptionDefinition>(_: Addon<Args, Id>): Addon<Args, Id>;
export declare function defineAddonOptions(): OptionBuilder<{}>;
// #endregion

// #region Variables
export declare const officialAddons: OfficialAddons;
// #endregion