/**
 * Generated by tsnapi — public API snapshot of `sv/src/testing`
 */
// #region Types
export type AddonTestCase<Addons extends AddonMap> = {
  variant: ProjectVariant;
  kind: {
    type: string;
    options: OptionMap<Addons>;
  };
};
export type CreateProject = (_: {
  testId: string;
  variant: ProjectVariant;
  clean?: boolean;
}) => string;
export type Fixtures = {
  page: Page;
  cwd(_: AddonTestCase<any>): string;
};
export type PlaywrightContext = Pick<typeof import("@playwright/test"), "chromium">;
export type PrepareServerOptions = {
  cwd: string;
  page: Page;
  buildCommand?: string;
  previewCommand?: string;
  expect?: VitestContext["expect"];
};
export type PrepareServerReturn = {
  url: string;
  close: () => Promise<void>;
};
export type ProjectVariant = "kit-js" | "kit-ts" | "vite-js" | "vite-ts";
export type SetupTestOptions<Addons extends AddonMap> = {
  kinds: Array<AddonTestCase<Addons>["kind"]>;
  filter?: (_: AddonTestCase<Addons>) => boolean;
  browser?: boolean;
  preAdd?: (_: {
    addonTestCase: AddonTestCase<Addons>;
    cwd: string;
  }) => Promise<void> | void;
};
export type VitestContext = Pick<typeof import("vitest"), "inject" | "test" | "beforeAll" | "beforeEach" | "expect">;
// #endregion

// #region Functions
export declare function createSetupTest(_: VitestContext, _?: PlaywrightContext): <Addons extends AddonMap>(_: Addons, _?: SetupTestOptions<Addons>) => {
  test: import("vitest").TestAPI<Fixtures>;
  testCases: Array<AddonTestCase<AddonMap>>;
  prepareServer: typeof prepareServer;
};
export declare function prepareServer({
  cwd,
  page,
  buildCommand,
  previewCommand,
  expect
}: PrepareServerOptions): Promise<PrepareServerReturn>;
export declare function setupGlobal({
  TEST_DIR,
  pre,
  post
}: {
  TEST_DIR: string;
  pre?: () => Promise<void>;
  post?: () => Promise<void>;
}): ({
  provide
}: TestProject) => Promise<() => Promise<void>>;
// #endregion

// #region Variables
export declare const variants: ProjectVariant[];
// #endregion