import { defineMigrationTask } from '../../../index.ts';

const REPORT_PATH = 'MIGRATION_TASKS.md';
const GUIDE_URL =
	'https://github.com/sveltejs/kit/blob/24a438d23baa049fcd1d6b4b558634f7054de052/documentation/docs/60-appendix/35-migrating-to-sveltekit-3.md';
const CODE_FILES = '**/*.{js,ts,svelte,mjs,mts,cjs,cts}';
export const GENERATED_MARKER =
	'<!-- Generated by sv migrate sveltekit-3:collect-migration-instructions -->';

type MigrationTask = {
	title: string;
	checks: Array<{
		include: string | string[];
		patterns: Array<string | RegExp>;
	}>;
	summary: string;
	instructions: string;
	links: Array<{ label: string; url: string }>;
};

function guideLink(anchor: string): MigrationTask['links'] {
	return [{ label: 'Migrating to SvelteKit v3', url: `${GUIDE_URL}#${anchor}` }];
}

const migrationTasks: MigrationTask[] = [
	{
		title: 'Migrate remaining `$app/stores` usages',
		checks: [
			{
				include: CODE_FILES,
				patterns: ['$app/stores']
			}
		],
		summary:
			'The automatic migration can leave `$app/stores` references when their store semantics require application context.',
		instructions:
			'Replace each remaining `$app/stores` reference with `$app/state`. Remove auto-subscription prefixes, read `page` and `navigating` directly, and use `updated.current`. Rewrite `getStores()`, `get(store)`, subscriptions, re-exports, and dynamic imports according to how the value is used rather than only changing the module name.',
		links: guideLink('appstores-removed')
	},
	{
		title: 'Migrate the removed `$service-worker` module',
		checks: [
			{
				include: CODE_FILES,
				patterns: ['$service-worker']
			}
		],
		summary:
			'SvelteKit 3 removes `$service-worker` and replaces its exports with several new modules.',
		instructions:
			'Import `version` from `$app/env`, application asset metadata from `$app/manifest`, and path helpers from `$app/paths`. Account for the new manifest value shapes rather than blindly renaming `build` or `files` imports.',
		links: guideLink('service-worker-removed')
	},
	{
		title: 'Create a TypeScript project for the service worker',
		checks: [
			{
				include: ['src/service-worker.ts', 'src/service-worker/**/*.ts'],
				patterns: [/\S/]
			}
		],
		summary:
			'TypeScript service workers now need a separate project with service-worker-specific types.',
		instructions:
			'Exclude the service worker from the root tsconfig and ensure `src/service-worker/tsconfig.json` extends `$app/tsconfig/service-worker`. Move a flat `src/service-worker.ts` entry to `src/service-worker/index.ts` if necessary, preserving any tooling references.',
		links: guideLink('apptsconfigservice-worker')
	},
	{
		title: 'Make the service worker module-compatible',
		checks: [
			{
				include: ['src/service-worker.{js,ts}', 'src/service-worker/**/*.{js,ts}'],
				patterns: [/\bimportScripts\s*\(/]
			}
		],
		summary:
			'SvelteKit 3 registers service workers as modules, where classic worker APIs may not work.',
		instructions:
			'Replace `importScripts(...)` and any other classic-worker-only assumptions with module imports or module-compatible equivalents.',
		links: guideLink('service-worker-registrations-use-type-module')
	},
	{
		title: 'Copy `page.url` before mutating it',
		checks: [
			{
				include: CODE_FILES,
				patterns: [
					/\bpage\s*\.\s*url\s*\.\s*searchParams\s*\.\s*(?:append|delete|set|sort)\s*\(/,
					/\bpage\s*\.\s*url\s*\.\s*(?:hash|host|hostname|href|password|pathname|port|protocol|search|username)\s*(?:=|\+\+|--)/
				]
			}
		],
		summary: '`page.url` and its search parameters are readonly in SvelteKit 3.',
		instructions:
			'Create a mutable copy with `new URL(page.url.href)`, mutate that copy, and use it for navigation or serialization. Leave readonly accesses unchanged.',
		links: guideLink('pageurl-is-now-readonly')
	},
	{
		title: 'Review `goto` destinations',
		checks: [
			{
				include: CODE_FILES,
				patterns: [/(?=[\s\S]*['"]\$app\/navigation['"])(?=[\s\S]*\bgoto\s*\()/]
			}
		],
		summary: '`goto(...)` now rejects destinations that do not resolve to an application route.',
		instructions:
			'Confirm each destination is an internal route. Use `window.location.href` for external browser navigation, and handle rejected dynamic destinations where they can fail to resolve.',
		links: guideLink('goto-rejects-for-urls-that-dont-resolve-to-a-route')
	},
	{
		title: 'Guard navigation `delta` access',
		checks: [
			{
				include: CODE_FILES,
				patterns: [
					/(?=[\s\S]*['"]\$app\/navigation['"])(?=[\s\S]*(?:\.\s*delta\b|\{[^}]*\bdelta\b))/
				]
			}
		],
		summary: 'Navigation `delta` is now only defined for `popstate` navigations.',
		instructions:
			'Check the navigation type or handle `undefined` before using `delta`. Do not treat an absent delta as zero unless that has the intended application meaning.',
		links: guideLink('delta-only-exists-for-popstate-navigations')
	},
	{
		title: 'Handle `preloadData` errors',
		checks: [
			{
				include: CODE_FILES,
				patterns: [/(?=[\s\S]*['"]\$app\/navigation['"])(?=[\s\S]*\bpreloadData\s*\()/]
			}
		],
		summary:
			'`preloadData(...)` can now return an error result, and redirects report their real status.',
		instructions:
			'Inspect the complete result flow and add handling for `{ type: "error", status, error }` where absent. Do not assume every non-redirect result is loaded or has status 200.',
		links: guideLink('preloaddata-can-return-an-error-result')
	},
	{
		title: 'Review enhanced forms with explicit actions',
		checks: [
			{
				include: '**/*.svelte',
				patterns: [/(?=[\s\S]*\buse:enhance\b)(?=[\s\S]*<form\b[^>]*\baction\s*=)/]
			}
		],
		summary: 'Enhanced forms that submit to another page now navigate to that page.',
		instructions:
			'Determine whether each action resolves to another page and confirm navigation is intended. If the form must remain on the current page, implement that behavior explicitly in the enhancement callback.',
		links: guideLink('appforms')
	},
	{
		title: 'Migrate `handleValidationError`',
		checks: [
			{
				include: '**/hooks*.{js,ts,mjs,mts}',
				patterns: ['handleValidationError']
			}
		],
		summary: '`handleValidationError` is removed in SvelteKit 3.',
		instructions:
			'Move validation-error handling into `handleError` and branch on `kind === "validation"`. Merge it carefully with any existing `handleError` logic.',
		links: guideLink('handlevalidationerror-is-removed')
	},
	{
		title: 'Review `handleError` behavior',
		checks: [
			{
				include: '**/hooks*.{js,ts,mjs,mts}',
				patterns: ['handleError']
			}
		],
		summary: 'SvelteKit 3 sends expected, validation, and rendering errors through `handleError`.',
		instructions:
			'Review filtering, logging, reporting, returned error properties, and status handling for the broader set of errors. If `hooks.client` has an async hook, enable `compilerOptions.experimental.async` in `sveltekit(...)`.',
		links: guideLink('handleerror-receives-all-errors')
	},
	{
		title: 'Remove the Node polyfills import',
		checks: [
			{
				include: CODE_FILES,
				patterns: ['@sveltejs/kit/node/polyfills']
			}
		],
		summary: '`@sveltejs/kit/node/polyfills` is removed because SvelteKit 3 requires modern Node.',
		instructions:
			'Remove the obsolete side-effect import and verify that the custom server or adapter runs on Node 22.17 or newer.',
		links: guideLink('sveltejskitnodepolyfills-removed')
	},
	{
		title: 'Remove `await` from synchronous Node helpers',
		checks: [
			{
				include: CODE_FILES,
				patterns: [
					/(?=[\s\S]*['"]@sveltejs\/kit\/node['"])(?=[\s\S]*\bawait\s+(?:\w+\.)?(?:getRequest|setResponse)\s*\()/
				]
			}
		],
		summary: '`getRequest` and `setResponse` from `@sveltejs/kit/node` are now synchronous.',
		instructions:
			'Remove `await` only from calls bound to those SvelteKit helpers, then review surrounding promise composition and return types.',
		links: guideLink('sveltejskitnode')
	},
	{
		title: 'Rename cookie option types',
		checks: [
			{
				include: CODE_FILES,
				patterns: ['CookieSerializeOptions', 'CookieParseOptions']
			}
		],
		summary: 'Cookie v2 renames its serialization and parsing option types.',
		instructions:
			'Rename `CookieSerializeOptions` to `SerializeOptions` and `CookieParseOptions` to `ParseOptions`, changing only types imported from the `cookie` package.',
		links: guideLink('updated-to-cookie-v2')
	},
	{
		title: 'Replace non-ASCII cookie names',
		checks: [
			{
				include: CODE_FILES,
				patterns: [
					// eslint-disable-next-line no-control-regex
					/\bcookies\s*\.\s*(?:get|getAll|set|delete|serialize)\s*\(\s*['"][^'"]*[^\x00-\x7f][^'"]*['"]/
				]
			}
		],
		summary: 'Cookie v2 rejects cookie names containing non-ASCII characters.',
		instructions:
			'Choose a stable ASCII replacement and consider compatibility or cleanup for cookies already issued under the old name.',
		links: guideLink('updated-to-cookie-v2')
	},
	{
		title: 'Rename Cloudflare `platform.context`',
		checks: [
			{
				include: CODE_FILES,
				patterns: [/\bplatform\s*(?:\?\.|\.)\s*context\b/]
			}
		],
		summary: 'The Cloudflare adapter replaces `platform.context` with `platform.ctx`.',
		instructions:
			'Confirm the value is the Cloudflare platform execution context, then rename it to `platform.ctx` and update related platform typings.',
		links: guideLink('adapter-cloudflare')
	},
	{
		title: 'Move adapter-node `ORIGIN` to `paths.origin`',
		checks: [
			{
				include: ['Dockerfile*', '**/Dockerfile*', '**/*.{js,ts,mjs,mts,json,jsonc,yml,yaml,toml}'],
				patterns: [
					/\bprocess\.env\.ORIGIN\b/,
					/\benv\s*\[\s*['"]ORIGIN['"]\s*\]/,
					/^\s*(?:ENV|ARG)\s+ORIGIN\b/m,
					/^\s*ORIGIN\s*[:=]/m
				]
			}
		],
		summary: 'The adapter-node `ORIGIN` environment variable is removed.',
		instructions:
			'If this value configures adapter-node, move the public-facing origin to `paths.origin` in `sveltekit(...)`. Remove the environment variable only after confirming it has no unrelated use.',
		links: guideLink('adapter-node')
	},
	{
		title: 'Replace the Vercel edge runtime',
		checks: [
			{
				include: '**/*.{js,ts,mjs,mts,json,jsonc}',
				patterns: [/\bruntime\s*:\s*['"]edge['"]/]
			}
		],
		summary: 'The Vercel adapter no longer supports the edge runtime.',
		instructions:
			'Select a supported Vercel runtime and review runtime-specific APIs, dependencies, and deployment behavior before changing the configuration.',
		links: guideLink('adapter-vercel')
	},
	{
		title: 'Replace `builder.createEntries` in custom adapters',
		checks: [
			{
				include: CODE_FILES,
				patterns: [/\bbuilder\s*\.\s*createEntries\s*\(/]
			}
		],
		summary: 'The adapter API removes `builder.createEntries`.',
		instructions:
			'Replace it with the appropriate `builder.writeClient`, `builder.writeServer`, and `builder.writePrerendered` flow for the adapter output model.',
		links: guideLink('adapter-api-changes')
	},
	{
		title: 'Remove request route data from remote queries',
		checks: [
			{
				include: ['**/*.remote.{js,ts}', '**/*.remote.*.{js,ts}', '**/remote.{js,ts}'],
				patterns: [/\bevent\s*\.\s*(?:url|params|route)\b/]
			}
		],
		summary: 'Remote queries can no longer access `event.url`, `event.params`, or `event.route`.',
		instructions:
			'Pass the required values explicitly as validated query arguments and remove the request-specific event access.',
		links: guideLink('eventurl-eventparams-and-eventroute-cannot-be-accessed-inside-queries')
	},
	{
		title: 'Use remote form field attributes',
		checks: [
			{
				include: '**/*.svelte',
				patterns: [
					/(?=[\s\S]*(?:from\s*['"][^'"]+\.remote(?:\.[^'"]+)?['"]|import\(\s*['"][^'"]+\.remote))(?=[\s\S]*\bname\s*=)/
				]
			}
		],
		summary: 'Remote form controls must use attributes from the current form field.',
		instructions:
			'Replace manually specified control names with attributes from the corresponding field `.as(...)` method, verifying that the field belongs to the submitted form.',
		links: guideLink('form-submissions-require-fieldas')
	},
	{
		title: 'Review consumers of 204 responses',
		checks: [
			{
				include: ['src/routes/**/+server.{js,ts}', '**/*.{test,spec}.{js,ts,mjs,mts}'],
				patterns: [/\bstatus\s*:\s*204\b/]
			}
		],
		summary: 'SvelteKit 3 returns no body for 204 and other empty 2xx responses.',
		instructions:
			'Find callers and tests for the matched endpoint and ensure they do not parse JSON or text from its empty response. Keep the endpoint response unchanged if it is already spec-compliant.',
		links: guideLink('204-responses-return-no-content')
	},
	{
		title: 'Replace remaining `csrf.checkOrigin` configuration',
		checks: [
			{
				include: '**/{svelte,vite}.config.{js,ts,mjs,mts,cjs,cts}',
				patterns: ['checkOrigin']
			}
		],
		summary: '`csrf.checkOrigin` is removed and CSRF protection is always enabled.',
		instructions:
			'Remove `checkOrigin`. If cross-origin submissions are intentional, configure the narrowest possible `csrf.trustedOrigins` allowlist instead of disabling protection.',
		links: guideLink('csrfcheckorigin-replaced-by-csrftrustedorigins')
	},
	{
		title: 'Review cross-origin form submissions',
		checks: [
			{
				include: '**/*.svelte',
				patterns: [/<form\b[^>]*\baction\s*=\s*['"](?:https?:)?\/\//]
			}
		],
		summary: 'Cross-origin mutative requests without a `Content-Type` header are rejected as CSRF.',
		instructions:
			'Ensure the submission sends an appropriate `Content-Type` header or add the destination to the narrowest possible `csrf.trustedOrigins` allowlist.',
		links: guideLink('cross-origin-form-submissions-require-a-content-type-header')
	}
];

type Finding = { task: MigrationTask; files: string[] };

export default defineMigrationTask({
	id: 'collect-migration-instructions',
	description: 'Collect instructions for non-automated migration tasks',
	run: ({ sv }) => {
		const findings: Finding[] = [];

		for (const task of migrationTasks) {
			const files = new Set<string>();
			for (const check of task.checks) {
				sv.files(
					{
						include: check.include,
						exclude: [REPORT_PATH],
						where: (content) => check.patterns.some((pattern) => matches(content, pattern))
					},
					(_content, file) => {
						files.add(file);
						return false;
					}
				);
			}

			if (files.size > 0) findings.push({ task, files: [...files].sort() });
		}

		if (findings.length === 0) return;

		sv.file(REPORT_PATH, (content) => {
			if (content && !content.includes(GENERATED_MARKER)) {
				throw new Error(
					`'${REPORT_PATH}' already exists and was not generated by this migration. Move or rename it before rerunning the task.`
				);
			}

			return renderReport(findings);
		});
	}
});

function matches(content: string, pattern: string | RegExp): boolean {
	return typeof pattern === 'string' ? content.includes(pattern) : pattern.test(content);
}

export function renderReport(findings: Finding[]): string {
	const sections = findings.map(({ task, files }) => {
		const links = task.links.map(({ label, url }) => `- [${label}](${url})`).join('\n');
		const locations = files.map((file) => `- [ ] \`${file}\``).join('\n');

		return `### ${task.title}

${task.summary}

#### What to do

${task.instructions}

#### References

${links}

#### Files to review

${locations}`;
	});

	return `${GENERATED_MARKER}
# SvelteKit 3 migration tasks

Some migrations are uncommon, context-dependent, or disproportionately difficult to automate safely. This document lists them.

The findings are intentionally broad and may include files that do not require changes.

AI agents can work through the migration tasks below one at a time:

1. Read the linked documentation or pull request before changing code.
2. Inspect every listed file and its surrounding context.
3. Ignore a finding when the file is not actually affected.
4. Make the smallest necessary change. Do not perform unrelated refactors or introduce unnecessary abstractions.
5. Ask the user when application intent cannot be inferred.
6. Run the project's appropriate checks after editing.

Also search the project for \`@migration-task\` comments. They may describe additional manual migration work that must be resolved.

## Migration tasks

${sections.join('\n\n')}

## Final verification

- [ ] Review every migration task and ignore any irrelevant findings.
- [ ] Resolve remaining \`@migration-task\` comments.
- [ ] Run the project's type checker and tests.
- [ ] Build the project successfully.
- [ ] Delete this file when all migration work is complete.
`;
}
