/**
 * Generated by tsnapi — public API snapshot of `@sveltejs/sv-utils`
 */
// #region Types
export type ConfigFileReader = (_: string) => string | null;
export type Package = {
  name: string;
  version: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  bugs?: string;
  repository?: {
    type: string;
    url: string;
  };
  keywords?: string[];
  workspaces?: string[];
};
export type SvelteConfigKind = "svelte" | "vite";
export type SvelteConfigLocation = {
  path: SvelteConfigPath;
  kind: SvelteConfigKind;
};
export type SvelteConfigObjects = {
  location: SvelteConfigLocation;
  config: estree.ObjectExpression;
  kit: estree.ObjectExpression;
};
export type TransformFn = (_: string) => string;
export type YamlDocument = {
  get(_: string): unknown;
  set(_: string, _: unknown): void;
};
// #endregion

// #region Classes
export declare class Comments {
  private original;
  private leading;
  private trailing;
  constructor();
  add(_: BaseNode$1, _: CommentType, _?: {
    position?: "leading" | "trailing";
  }): void;
  remove(_: (_: estree.Comment) => boolean | undefined | null): void;
}
// #endregion

// #region Namespaces
export declare namespace css {
  export { addAtRule, addDeclaration, addImports, addRule };
}
export declare namespace html {
  export { addAttribute, addFromRawHtml, appendElement, createElement, insertElement };
}
export declare namespace js {
  export { array_d_exports as array, common_d_exports as common, exports_d_exports as exports, function_d_exports as functions, imports_d_exports as imports, kit_d_exports as kit, object_d_exports as object, variables_d_exports as variables, vite_d_exports as vite };
}
export declare namespace json {
  export { arrayUpsert, packageScriptsUpsert };
}
export declare namespace pnpm {
  export { allowBuilds, onlyBuiltDependencies };
}
export declare namespace svelte {
  export { RootWithInstance, addFragment, addSlot, ensureScript };
}
export declare namespace text {
  export { upsert };
}
// #endregion

// #region Functions
export declare function coerceVersion(_: string): Version;
export declare function createPrinter(..._: boolean[]): Printer[];
export declare function defineEnv({
  sv,
  cwd,
  dependencyVersion
}: DefineEnvContext): DefineEnv;
export declare function fileExists(_: string, _: string): boolean;
export declare function isVersionUnsupportedBelow(_: string, _: string): boolean | undefined;
export declare function loadFile(_: string, _: string): string;
export declare function loadPackageJson(_: string): {
  source: string;
  data: Package;
};
export declare function minVersion(_: string): string;
export declare function resolveCommandArray(_: Agent, _: Command, _: string[]): string[];
export declare function sanitizeName(_: string, _: "package" | "wrangler"): string;
export declare function saveFile(_: string, _: string, _: string): void;
/** @deprecated */
export declare function splitVersion(_: string): Version;
// #endregion

// #region Variables
export declare const color: {
  addon: (str: ColorInput) => string;
  command: (str: ColorInput) => string;
  env: (str: ColorInput) => string;
  path: (str: ColorInput) => string;
  route: (str: ColorInput) => string;
  website: (str: ColorInput) => string;
  optional: (str: ColorInput) => string;
  dim: (str: ColorInput) => string;
  success: (str: ColorInput) => string;
  warning: (str: ColorInput) => string;
  error: (str: ColorInput) => string;
  hidden: (str: ColorInput) => string;
};
export declare const dedent: Dedent;
export declare const downloadJson: (url: string) => Promise<any>;
export declare const parse: {
  css: typeof parseCss;
  html: typeof parseHtml;
  json: typeof parseJson;
  script: typeof parseScript;
  svelte: typeof parseSvelte;
  toml: typeof parseToml;
  yaml: typeof parseYaml;
};
export declare const svelteConfig: {
  edit: (target: {
    sv: SvFileApi;
    cwd: string;
  }, editFn: SvelteConfEdit) => void;
  find: (source: ConfigSource) => SvelteConfigLocation | null;
  read: (source: ConfigSource) => SvelteConfigObjects | null;
};
export declare const transforms: {
  script(cb: (file: {
    ast: estree.Program;
    comments: Comments;
    content: string;
    js: typeof index_d_exports$3;
  }) => void | false, options?: TransformOptions): (content: string) => string;
  svelte(cb: (file: {
    ast: SvelteAst.Root;
    content: string;
    svelte: typeof index_d_exports$4;
    js: typeof index_d_exports$3;
  }) => void | false, options?: TransformOptions): (content: string) => string;
  svelteScript(scriptOptions: {
    language: "ts" | "js";
  }, cb: (file: {
    ast: RootWithInstance;
    content: string;
    svelte: typeof index_d_exports$4;
    js: typeof index_d_exports$3;
  }) => void | false, options?: TransformOptions): TransformFn;
  css(cb: (file: {
    ast: Omit<SvelteAst.CSS.StyleSheetBase, "attributes" | "content">;
    content: string;
    css: typeof index_d_exports$1;
  }) => void | false, options?: TransformOptions): TransformFn;
  json<T = any>(cb: (file: {
    data: T;
    content: string;
    json: typeof json_d_exports;
  }) => void | false, options?: TransformOptions): TransformFn;
  yaml(cb: (file: {
    data: YamlDocument;
    content: string;
  }) => void | false, options?: TransformOptions): TransformFn;
  toml(cb: (file: {
    data: TomlTable;
    content: string;
  }) => void | false, options?: TransformOptions): TransformFn;
  html(cb: (file: {
    ast: SvelteAst.Fragment;
    content: string;
    html: typeof index_d_exports$2;
  }) => void | false, options?: TransformOptions): TransformFn;
  text(cb: (file: {
    content: string;
    text: typeof text_d_exports;
  }) => string | false): TransformFn;
};
// #endregion

// #region Other
export { AgentName }
export { AGENTS }
export { estree as AstTypes }
export { COMMANDS }
export { constructCommand }
export { detect }
export { resolveCommand }
export { SvelteAst }
export { index_d_exports as Walker }
// #endregion