// THIS FILE IS GENERATED BY `scripts/bundle-community.js`
export type CommunityAdder = {
	name: string;
	id: string;
	description: string;
	category: string;
	npm: string;
	repo: string;
	github: string;
	website: string;
	logo: string;
};

export const communityAdders: CommunityAdder[] = [
	{
		name: 'UnoCSS',
		id: 'unocss',
		description: 'The instant on-demand Atomic CSS engine',
		category: 'CSS',
		npm: 'unocss-svelte-integration',
		repo: 'owner-name/repo-name',
		github: 'https://github.com/.../...',
		website: 'https://unocss.dev',
		logo: 'unocss.svg'
	},
	{
		name: 'unplugin-icons',
		id: 'unplugin-icons',
		description: 'Access thousands of icons as components on-demand universally',
		category: 'Icons',
		npm: 'unplugin-icons-svelte-integration',
		repo: 'owner-name/repo-name',
		github: 'https://github.com/.../...',
		website: 'https://www.npmjs.com/package/unplugin-icons',
		logo: 'unplugin-icons.svg'
	}
];
