name: Update Template Repo (manual)

on:
  workflow_dispatch:

permissions: {}
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/cli'
    name: Update template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run template update script
        run: pnpm -F @sveltejs/create update-template-repo
        env:
          UPDATE_TEMPLATE_SSH_KEY: ${{ secrets.UPDATE_TEMPLATE_SSH_KEY }}
